name: 📚 Documentation Improvement
description: Report missing or incorrect documentation
title: "[Docs]: "
labels: ["documentation"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What part of the documentation is missing or incorrect?
    validations:
      required: true
  - type: input
    id: link
    attributes:
      label: Link to documentation
      description: URL of the page that needs improvement